local function asnip(trigger)
  return { trig = trigger, wordTrig = false, snippetType='autosnippet'}
end

return {
  s(asnip('//'), fmta([[\frac{<>}{<>}]], { i(1), i(2) })),
  s(asnip('..'), t('\\ldots')),
  s(asnip(':='), t('\\coloneqq')),
  s(asnip(';ep'), fmta([[^{<>}]], { i(1) })),
  s(asnip(';lim'), fmta([[\lim_{<>}]], { i(1) })),
  s(asnip(';int'), fmta([[\int_{<>}]], { i(1) })),
  s(asnip(';us'), fmta([[_{<>}]], { i(1) })),
  s(asnip(';im'), fmta([[$<>$]], { i(1) })),
  s(asnip(';id'), t('\\id')),
  s(asnip(';se'), fmta([[\{<>\}]], { i(1) })),
  s(asnip(';2'), fmta([[\sqrt{<>}]], { i(1) })),
  s(asnip(';<'), fmta([[\langle <> \rangle]], { i(1) })),
  s(asnip(';dm'), { t({'\\[', '    '}), i(1), t({'','\\]'}) }),
  s(asnip(';inv'), t('^{-1}')),
  s(asnip(';norm'), fmta([[\Vert <> \Vert]], { i(1) })),
  s(asnip(';0'), t('\\varnothing')),
  s(asnip(';6'), t('\\partial')),
  s(asnip(';8'), t('\\infty')),
  s(asnip(';\\'), t('\\setminus')),
  s(asnip(';.'), t('\\cdot')),
  s(asnip(';*'), t('\\times')),
  s(asnip(';['), t('\\subseteq')),
  s(asnip(';]'), t('\\supseteq')),
  s(asnip(';('), t('\\subset')),
  s(asnip(';)'), t('\\supset')),

  s(asnip(';aj'), t('\\downarrow')),
  s(asnip(';ak'), t('\\uparrow')),
  s(asnip(';ah'), t('\\leftarrow')),
  s(asnip(';al'), t('\\to')),
  s(asnip(';am'), t('\\mapsto')),

  s(asnip(';ga'), t('\\alpha')),
  s(asnip(';gb'), t('\\beta')),
  s(asnip(';gc'), t('\\chi')),
  s(asnip(';gd'), t('\\delta')),
  s(asnip(';ge'), t('\\epsilon')),
  s(asnip(';gf'), t('\\phi')),
  s(asnip(';gg'), t('\\gamma')),
  s(asnip(';gn'), t('\\eta')),
  s(asnip(';gi'), t('\\iota')),
  s(asnip(';gk'), t('\\kappa')),
  s(asnip(';gl'), t('\\lambda')),
  s(asnip(';gm'), t('\\mu')),
  s(asnip(';gn'), t('\\nu')),
  s(asnip(';gp'), t('\\pi')),
  s(asnip(';go'), t('\\theta')),
  s(asnip(';gr'), t('\\rho')),
  s(asnip(';gs'), t('\\sigma')),
  s(asnip(';gt'), t('\\tau')),
  s(asnip(';gy'), t('\\psi')),
  s(asnip(';gu'), t('\\upsilon')),
  s(asnip(';gw'), t('\\omega')),
  s(asnip(';gz'), t('\\zeta')),
  s(asnip(';gx'), t('\\xi')),

  s(asnip(';gD'), t('\\Delta')),
  s(asnip(';gF'), t('\\Phi')),
  s(asnip(';gG'), t('\\Gamma')),
  s(asnip(';gL'), t('\\Lambda')),
  s(asnip(';gO'), t('\\Theta')),
  s(asnip(';gP'), t('\\prod')),
  s(asnip(';gY'), t('\\Psi')),
  s(asnip(';gU'), t('\\Upsilon')),
  s(asnip(';gW'), t('\\Omega')),
  s(asnip(';gX'), t('\\Xi')),

  s(asnip(';gve'), t('\\varepsilon')),
  s(asnip(';gvf'), t('\\varphi')),
  s(asnip(';gvk'), t('\\varkappa')),
  s(asnip(';gvp'), t('\\varpi')),
  s(asnip(';gvo'), t('\\vartheta')),
  s(asnip(';gvr'), t('\\varrho')),
}
