vim.keymap.set('n', '<localleader>lii', '<plug>(vimtex-info)', {buffer = true})
vim.keymap.set('n', '<localleader>liI', '<plug>(vimtex-info-full)', {buffer = true})
vim.keymap.set('n', '<localleader>lit', '<plug>(vimtex-toc-open)', {buffer = true})
vim.keymap.set('n', '<localleader>liT', '<plug>(vimtex-toc-toggle)', {buffer = true})
vim.keymap.set('n', '<localleader>lil', '<plug>(vimtex-log)', {buffer = true})
vim.keymap.set('n', '<localleader>lfv', '<plug>(vimtex-view)', {buffer = true})
vim.keymap.set('n', '<localleader>lfr', '<plug>(vimtex-reverse-search)', {buffer = true})
vim.keymap.set('n', '<localleader>ll', '<plug>(vimtex-compile)', {buffer = true})
vim.keymap.set({'n','x'}, '<localleader>lL', '<plug>(vimtex-compile-selected)', {buffer = true})
vim.keymap.set('n', '<localleader>lck', '<plug>(vimtex-stop)', {buffer = true})
vim.keymap.set('n', '<localleader>lcK', '<plug>(vimtex-stop-all)', {buffer = true})
vim.keymap.set('n', '<localleader>lce', '<plug>(vimtex-errors)', {buffer = true})
vim.keymap.set('n', '<localleader>lco', '<plug>(vimtex-compile-output)', {buffer = true})
vim.keymap.set('n', '<localleader>lgs', '<plug>(vimtex-status)', {buffer = true})
vim.keymap.set('n', '<localleader>lgS', '<plug>(vimtex-status-all)', {buffer = true})
vim.keymap.set('n', '<localleader>lgc', '<plug>(vimtex-clean)', {buffer = true})
vim.keymap.set('n', '<localleader>lgC', '<plug>(vimtex-clean-full)', {buffer = true})
vim.keymap.set('n', '<localleader>lgr', '<plug>(vimtex-reload)', {buffer = true})
vim.keymap.set('n', '<localleader>lgR', '<plug>(vimtex-reload-state)', {buffer = true})
vim.keymap.set('n', '<localleader>lgm', '<plug>(vimtex-toggle-main)', {buffer = true})
vim.keymap.set('n', '<localleader>lgc', '<plug>(vimtex-contex-menu)', {buffer = true})

vim.keymap.set('n', '<localleader>lsde', '<plug>(vimtex-env-delete)', {buffer = true})
vim.keymap.set('n', '<localleader>lsdc', '<plug>(vimtex-cmd-delete)', {buffer = true})
vim.keymap.set('n', '<localleader>lsd$', '<plug>(vimtex-env-delete-math)', {buffer = true})
vim.keymap.set('n', '<localleader>lsdd', '<plug>(vimtex-delim-delete)', {buffer = true})

vim.keymap.set('n', '<localleader>sce', '<plug>(vimtex-env-change)', {buffer = true})
vim.keymap.set('n', '<localleader>scc', '<plug>(vimtex-cmd-change)', {buffer = true})
vim.keymap.set('n', '<localleader>sc$', '<plug>(vimtex-env-change-math)', {buffer = true})
vim.keymap.set('n', '<localleader>scd', '<plug>(vimtex-delim-change-math)', {buffer = true})

vim.keymap.set({'n','x'}, '<localleader>stf', '<plug>(vimtex-cmd-toggle-frac)', {buffer = true})
vim.keymap.set('n', '<localleader>stc', '<plug>(vimtex-cmd-toggle-star)', {buffer = true})
vim.keymap.set('n', '<localleader>sts', '<plug>(vimtex-env-toggle-star)', {buffer = true})
vim.keymap.set('n', '<localleader>ste', '<plug>(vimtex-env-toggle)', {buffer = true})
vim.keymap.set('n', '<localleader>st$', '<plug>(vimtex-env-toggle-math)', {buffer = true})
vim.keymap.set('n', '<localleader>stb', '<plug>(vimtex-env-toggle-break)', {buffer = true})

vim.keymap.set({'n','x'}, '<localleader>std', '<plug>(vimtex-delim-toggle-modifier)', {buffer = true})
vim.keymap.set({'n','x'}, '<localleader>stD', '<plug>(vimtex-delim-toggle-modifier-reverse)', {buffer = true})

vim.keymap.set({'n','x'}, '<localleader>lsac', '<plug>(vimtex-cmd-create)', {buffer = true})

--vim.keymap.set('n', 'localleader>se', '<plug>(vimtex-env-surround-line)')
vim.keymap.set('n', '<localleader>lse', '<plug>(vimtex-env-surround-operator)', {buffer = true})
vim.keymap.set('x', '<localleader>lse', '<plug>(vimtex-env-surround-visual)', {buffer = true})

vim.keymap.set({'x','o'}, 'ac', '<plug>(vimtex-ac)', {buffer = true})
vim.keymap.set({'x','o'}, 'ic', '<plug>(vimtex-ic)', {buffer = true})
vim.keymap.set({'x','o'}, 'ad', '<plug>(vimtex-ad)', {buffer = true})
vim.keymap.set({'x','o'}, 'ic', '<plug>(vimtex-ic)', {buffer = true})
vim.keymap.set({'x','o'}, 'ae', '<plug>(vimtex-ae)', {buffer = true})
vim.keymap.set({'x','o'}, 'ie', '<plug>(vimtex-ie)', {buffer = true})
vim.keymap.set({'x','o'}, 'a$', '<plug>(vimtex-a$)', {buffer = true})
vim.keymap.set({'x','o'}, 'i$', '<plug>(vimtex-i$)', {buffer = true})
vim.keymap.set({'x','o'}, 'aP', '<plug>(vimtex-aP)', {buffer = true})
vim.keymap.set({'x','o'}, 'iP', '<plug>(vimtex-iP)', {buffer = true})
vim.keymap.set({'x','o'}, 'am', '<plug>(vimtex-am)', {buffer = true})
vim.keymap.set({'x','o'}, 'im', '<plug>(vimtex-im)', {buffer = true})

vim.keymap.set({'n', 'x','o'}, '%', '<plug>(vimtex-%)', {buffer = true})
vim.keymap.set({'n','x','o'}, ']]', '<plug>(vimtex-]])', {buffer = true})
vim.keymap.set({'n','x','o'}, '][', '<plug>(vimtex-][)', {buffer = true})
vim.keymap.set({'n','x','o'}, '[]', '<plug>(vimtex-[])', {buffer = true})
vim.keymap.set({'n','x','o'}, '[[', '<plug>(vimtex-[[)', {buffer = true})
vim.keymap.set({'n','x','o'}, ']m', '<plug>(vimtex-]m)', {buffer = true})
vim.keymap.set({'n','x','o'}, ']M', '<plug>(vimtex-]M)', {buffer = true})
vim.keymap.set({'n','x','o'}, '[m', '<plug>(vimtex-[m)', {buffer = true})
vim.keymap.set({'n','x','o'}, '[M', '<plug>(vimtex-[M)', {buffer = true})
vim.keymap.set({'n','x','o'}, ']n', '<plug>(vimtex-]n)', {buffer = true})
vim.keymap.set({'n','x','o'}, ']N', '<plug>(vimtex-]N)', {buffer = true})
vim.keymap.set({'n','x','o'}, '[n', '<plug>(vimtex-[n)', {buffer = true})
vim.keymap.set({'n','x','o'}, '[N', '<plug>(vimtex-[N)', {buffer = true})
vim.keymap.set({'n','x','o'}, ']r', '<plug>(vimtex-]r)', {buffer = true})
vim.keymap.set({'n','x','o'}, ']R', '<plug>(vimtex-]R)', {buffer = true})
vim.keymap.set({'n','x','o'}, '[r', '<plug>(vimtex-[r)', {buffer = true})
vim.keymap.set({'n','x','o'}, '[R', '<plug>(vimtex-[R)', {buffer = true})
vim.keymap.set({'n','x','o'}, ']/', '<plug>(vimtex-]/)', {buffer = true})
vim.keymap.set({'n','x','o'}, ']*', '<plug>(vimtex-]star)', {buffer = true})
vim.keymap.set({'n','x','o'}, '[/', '<plug>(vimtex-[/)', {buffer = true})
vim.keymap.set({'n','x','o'}, '[*', '<plug>(vimtex-[star)', {buffer = true})
vim.keymap.set({'n','x','o'}, 'K', '<plug>(vimtex-doc-package)', {buffer = true})
